### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by windischb** [prepare/Espresso#45]
Hi!

Is there any howTo or something similar for this?
I can't get it to run....

If i just try the TestEspressoCore it gives following Error:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libespr': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Espresso.NativeV8JsInterOp.V8Init()
   at Espresso.JsBridge.V8Init() in C:\_Daten\Repos\Github\Espresso\src\0_Start\JsBridge.cs:line 18
   at TestEspressoCore.Program.Main(String[] args) in C:\_Daten\Repos\Github\Espresso\Tests\TestEspressoCore\Program.cs:line 13
```

If i try to compile libespr i'll get:
```
Cannot open include file: 'v8.h': No such file or directory
```

A little startup Help would be great!!

**Comment by prepare** [comment]
Hello @windischb ,
Sorry for late reply.

you need to build a libespr.dll first.


please see https://github.com/prepare/Espresso/issues/30
it provides the examples + screenshots of how to build the libespr
in macOS (https://github.com/CompilerLab/Espresso/issues/7),
 Linux (https://github.com/CompilerLab/Espresso/issues/6)  and Windows
(https://github.com/CompilerLab/Espresso/issues/8)

---

Concepts:
 
a libespr is a modified version of

1) v8 engine inside the nodejs => called Espresso-VE
or
2) a modified version nodejs.exe => called Espression-ND


---

First you must be the nodejs

then apply our 'patches' 

see the manually patching step in 

https://github.com/CompilerLab/Espresso/issues/12

, I also provide a 'semi-automate' patching tools =>https://github.com/prepare/Espresso/issues/30

**Comment by prepare** [comment]
The documentation will be added later 
:)
